// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8W--5ngidaKds1esczZjJm4KhWwzCG4',
    appId: '1:41216586734:web:26ddca348e3e5cb67214ff',
    messagingSenderId: '41216586734',
    projectId: 'hanascore',
    authDomain: 'hanascore.firebaseapp.com',
    storageBucket: 'hanascore.firebasestorage.app',
    measurementId: 'G-1WMB12NK3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WZTjaqyH-judPPysH_pxN8bPFyhHZYQ',
    appId: '1:41216586734:android:220969adda17f27c7214ff',
    messagingSenderId: '41216586734',
    projectId: 'hanascore',
    storageBucket: 'hanascore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaNtZS0K48bpUBsge0nJ71AHtD19Z5DKs',
    appId: '1:41216586734:ios:36736c428e2243bd7214ff',
    messagingSenderId: '41216586734',
    projectId: 'hanascore',
    storageBucket: 'hanascore.firebasestorage.app',
    iosBundleId: 'com.example.hanaScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaNtZS0K48bpUBsge0nJ71AHtD19Z5DKs',
    appId: '1:41216586734:ios:36736c428e2243bd7214ff',
    messagingSenderId: '41216586734',
    projectId: 'hanascore',
    storageBucket: 'hanascore.firebasestorage.app',
    iosBundleId: 'com.example.hanaScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG8W--5ngidaKds1esczZjJm4KhWwzCG4',
    appId: '1:41216586734:web:1bec85ef2d4818cd7214ff',
    messagingSenderId: '41216586734',
    projectId: 'hanascore',
    authDomain: 'hanascore.firebaseapp.com',
    storageBucket: 'hanascore.firebasestorage.app',
    measurementId: 'G-S9DLPZBQY8',
  );
}
